name: Compile SCSS

on:
  push:
    branches:
      - master

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: 🔎 Check out repo
        uses: actions/checkout@master

      - name: 📂 Make destination directory for compiled CSS
        run: mkdir -vp public/custom/css

      - name: 📃 [1/3]. Compile avatar.css from avatar.scss
        uses: gha-utilities/sass-build@v0.2.6
        with:
          source: custom/scss/avatar.scss
          destination: public/custom/css/avatar.css
      
      - name: 📃 [2/3]. Compile common.css from common.scss
        uses: gha-utilities/sass-build@v0.2.6
        with:
          source: custom/scss/common.scss
          destination: public/custom/css/common.css
      
      - name: 📃 [3/3]. Compile pages.css from pages.scss
        uses: gha-utilities/sass-build@v0.2.6
        with:
          source: custom/scss/pages.scss
          destination: public/custom/css/pages.css

      - name: 🎭 [1/2]. Copy robots.txt to public path
        run: cp robots.txt public

      - name: 🎭 [2/2]. Copy custom/img to public path
        run: cp -r custom/img public/custom

      - name: 🚀 Deploy on gh-pages branch
        #uses: JamesIvJamesIves/githubJamesIves/github-pages-deploy-action@releases/v3
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public

      - name: 🔄 Sync with S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEST_DIR: ${{ secrets.AWS_DEST_DIR }}
          SOURCE_DIR: public
