name: Build and Sync

on:
  push:
    branches:
      - master

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: 🔎 Check out repo
        uses: actions/checkout@master

      # - name: Set up Python 3.9
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.9
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install bs4
      #     if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # - name: Download avatar
      #   run: |
      #     python scripts/dl-bili-frame.py

      - name: 📂 Make destination directory for compiled CSS
        run: mkdir -vp public/custom/css
        
      - name: 🔧 Prepare Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          
      - name: 🔧 Install sass
        run: npm install -g sass

      - name: 📃 [1/1]. Compile index.css from index.scss
        run: sass custom/scss/index.scss public/custom/css/index.css --source-map --embed-sources --style compressed
#         uses: gha-utilities/sass-build@v0.4.8
#         with:
#           source: custom/scss/index.scss
#           destination: public/custom/css/index.css
#           sourceMap: true
#           sourceMapEmbed: true

      - name: 🎭 [1/2]. Copy robots.txt to public path
        run: cp robots.txt public

      - name: 🎭 [2/2]. Copy custom/img to public path
        run: cp -r custom/img public/custom

      #- name: 🚀 Deploy on gh-pages branch
      #  #uses: JamesIvJamesIves/githubJamesIves/github-pages-deploy-action@releases/v3
      #  uses: JamesIves/github-pages-deploy-action@3.5.7
      #  with:
      #    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #    BRANCH: gh-pages
      #    FOLDER: public

      - name: 🔄 Sync with Server
        uses: wangyucode/sftp-upload-action@v1.3.2
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password:  ${{ secrets.PASSWORD }}
          localDir: 'public'
          remoteDir: ${{ secrets.REMOTE_DIR }}
          
